-- TABLE
CREATE TABLE cliente ( id INTEGER NOT NULL PRIMARY KEY,nome VARCHAR(255) NOT NULL,idade INTEGER NOT NULL,rg VARCHAR(255) NOT NULL,cpf VARCHAR(255) NOT NULL);
 
-- INDEX
 
-- TRIGGER
 
-- VIEW
 
